# Generated by Django 3.0.8 on 2021-04-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210419_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sortno',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock_alert',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
