# Generated by Django 3.0.8 on 2021-04-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210421_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
