# Generated by Django 3.0.8 on 2021-04-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210421_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
