# Generated by Django 3.0.8 on 2021-05-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210422_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='by_card',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='by_trust',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='to_trust',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
