# Generated by Django 3.0.8 on 2021-05-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210503_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
