# Generated by Django 3.0.8 on 2021-05-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_list_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='list_total',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
