# Generated by Django 3.0.8 on 2021-05-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_list_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='to_trust',
            field=models.CharField(max_length=100),
        ),
    ]
