# Generated by Django 3.0.8 on 2021-05-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(max_length=220)),
                ('phone_number', models.CharField(max_length=30)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
