# Generated by Django 3.0.8 on 2021-05-20 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210519_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expire_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='product',
            name='profit_porc',
            field=models.FloatField(default=0.4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rounding',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
