# Generated by Django 3.0.8 on 2021-05-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210520_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='days',
            field=models.CharField(default='l', max_length=100),
            preserve_default=False,
        ),
    ]
