# Generated by Django 3.0.8 on 2021-05-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210520_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='days',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
